;; SICP Practice: 3-4
(define (make-account balance password)
  (define alarm 0)
  (define (withdraw amount)
	(if (>= balance amount)
		(begin (set! balance (- balance amount))
			   balance)
		"Insufficient funds"))
  (define (deposit m)
	(set! balance (+ balance m))
	balance)
  (define (call-the-cops)
	(error "You feeling lucky, punk?"))
  (define (dispatch p m)
	(if (eq? password p)
		(cond ((eq? m 'withdraw) withdraw)
			  ((eq? m 'deposit) deposit)
			  (else (error "Unknown request -- MAKE-ACCOUNT"
						   m)))
		(lambda (num)
			(if (< alarm 7)
				(begin (set! alarm (+ alarm 1))
					   "Incorrect password")
				(call-the-cops)))))
  dispatch)

(define acc (make-account 100 'secret-password))

(begin
  (display ((acc 'some-other-password 'withdraw) 50)) (newline)
  (display ((acc 'some-other-password 'withdraw) 50)) (newline)
  (display ((acc 'some-other-password 'withdraw) 50)) (newline)
  (display ((acc 'some-other-password 'withdraw) 50)) (newline)
  (display ((acc 'some-other-password 'withdraw) 50)) (newline)
  (display ((acc 'some-other-password 'withdraw) 50)) (newline)
  (display ((acc 'some-other-password 'withdraw) 50)) (newline)
  (display ((acc 'some-other-password 'withdraw) 50)) (newline)
  )
