;; SICP Practice: 3-7
(define (make-account balance password)
  (define alarm 0)
  (define (withdraw amount)
	(if (>= balance amount)
		(begin (set! balance (- balance amount))
			   balance)
		"Insufficient funds"))
  (define (deposit m)
	(set! balance (+ balance m))
	balance)
  (define (call-the-cops)
	(error "You feeling lucky, punk?"))
  (define (check-password pswd)
	(if (eq? password pswd)
		#t
		#f))
  (define (dispatch p m)
	(if (eq? password p)
		(cond ((eq? m 'withdraw) withdraw)
			  ((eq? m 'deposit) deposit)
			  ((eq? m 'check-password) check-password)
			  (else (error "Unknown request -- MAKE-ACCOUNT"
						   m)))
		(lambda (num)
		  (if (< alarm 7)
			  (begin (set! alarm (+ alarm 1))
					 "Incorrect password")
			  (begin (set! alarm 0)
					 (call-the-cops))))))
  dispatch)

(define (make-joint acc-name password new-password)
  (define alarm 0)
  (define (call-the-cops)
	(error "You feeling lucky, punk?"))
  (define pswd-calc
	(lambda (num)
	  (if (< alarm 7)
		  (begin (set! alarm (+ alarm 1))
				 "Incorrect password")
		  (begin (set! alarm 0)
				 (call-the-cops)))))
  (if (acc-name password 'check-password)
	  (lambda (p m)
		(if (eq? new-password p)
			(cond ((eq? m 'withdraw) (acc-name password 'withdraw))
				  ((eq? m 'deposit) (acc-name password 'deposit))
				  ((eq? m 'check-password) (acc-name password 'check-password))
				  (else (error "Unknown request -- MAKE-JOINT"
							   m)))
			pswd-calc))
	  pswd-calc))

(define peter-acc (make-account 100 'open-sesame))

(define paul-acc (make-joint peter-acc 'open-sesame 'rosebud))

(begin
  (display ((peter-acc 'open-sesame 'withdraw) 40)) (newline)  
  (display ((paul-acc 'rosebud 'deposit) 40)) (newline)
  (display ((peter-acc 'open-sesame 'deposit) 20)) (newline)
  (display ((paul-acc 'rosebud 'withdraw) 20)) (newline)
  (newline)
  (display ((paul-acc 'rosebu 'withdraw) 20)) (newline)
  (display ((paul-acc 'rosebu 'withdraw) 20)) (newline)
  (display ((paul-acc 'rosebu 'withdraw) 20)) (newline)
  (display ((paul-acc 'rosebu 'withdraw) 20)) (newline)
  (display ((paul-acc 'rosebu 'withdraw) 20)) (newline)
  (display ((paul-acc 'rosebu 'withdraw) 20)) (newline)
  (display ((paul-acc 'rosebu 'withdraw) 20)) (newline)
  (display ((paul-acc 'rosebu 'withdraw) 20)) (newline)
  )
